version: "3.5"
services:
  database_master:
    image: mysql:8.0.30
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysqldata_master:/var/lib/mysql
      - ./master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=my_db_user
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork

  database_slave_1:
    image: mysql:8.0.30
    container_name: "database_slave_1"
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - "3307:3306"
    volumes:
      - mysqldata_slave_1:/var/lib/mysql
      - ./slave1.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=my_db_user
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork

  database_slave_2:
    image: mysql:8.0.30
    container_name: "database_slave_2"
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - "3308:3306"
    volumes:
      - mysqldata_slave_2:/var/lib/mysql
      - ./slave2.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=my_db_user
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  mysqldata_master:
  mysqldata_slave_1:
  mysqldata_slave_2:


